### PR TITLE
Create version of logback appender with AWS SDK v2 dependencies

### PR DESCRIPTION
**Pull request by valters**
Hi,

I am using AWS SDK v2 for some green-field projects, and thought it would be nice to to have the cloudwatch appender also use v2 dependencies.

For the appender it would mean maintaing/releasing two versions. (This should not be merged to master, but to some aws-v2 branch to be maintained in parallel with v1 stream.)

Note I could not figure out replacement for the ClientConfig, so I removed it for now. In AWS SDK v2 they (among other things) seem to have hidden the proxy overrides, etc, somewhere in http client config, but I was not able to find it.

### CODE REVIEW

**Comment by dibog** [comment]
Hi @valters 

I moved your fork into my rep as branch aws-v2. I want to evaluate it a bit more before I merge it.
Thank you very much for you contribution. 

(I have to think about if it makes sense to keep both versions (aws-v1 and aws-v2) or if I move to aws-v2.

**Comment by valters** [comment]
The AWS SDK v2 is a huge departure over v1, everything is changed. Mind you, v2 looks modern and I love it. But my opinion also is that v1 will continue to be maintained almost indefinitely.

They way v1 and v2 are designed, the artifacts actually could be used side-by-side. So I guess a piece-by-piece migration is doable. But a lot of people will simply never upgrade, because v1 simply is "good enough".

**Comment by dibog** [comment]
I still wondering how to keep both AWS versions. Currently I have put your changes into a branch and thought about to use version 1.* for the old version and 2.* for the AWS v2 version. What do you think?

(I still need to test the AWS v2 stuff behind a corporate firewall and see how the missing ClientConfig worsk there)

**Comment by valters** [comment]
Yes, I am all for releasing 2.* for using with AWS v2. Thanks!

The client config seems to be renamed to ProxyConfig. https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#132-client-http-proxy-configuration

(I don't have a proxy, so I would have hard time testing.)

**Comment by dibog** [comment]
Hello @valters,

could you please have a look at 

<dependency>
    <groupId>io.github.dibog</groupId>
    <artifactId>cloudwatch-logback-appender</artifactId>
    <version>2.0.0</version>
</dependency>

You can find the README here: 
https://github.com/dibog/cloudwatch-logback-appender/blob/aws-v2/README.md

Cheers, 
Dieter

**Comment by dibog** [comment]
I'll open an issue to discuss the AWS SDK V2 here:
https://github.com/dibog/cloudwatch-logback-appender/issues/11

**Comment by dibog** [comment]
I'll have merged your changes manually and will close this merge request.

**Pull request closed without merging**
