### PR TITLE
Fix issue with loading clientConfig settings

### PR DESCRIPTION
**Pull request by alitz**

### CODE REVIEW

**Comment by dibog** [comment]
Hi @alitz,

thanks for your pull request. Could you please describe when an empty (default constructed ClientContext) leads to problems for you? I would like to understand the difference between it being null (your fix) and it being just default constructored (my assumption).

Best regards,
Dieter

**Comment by alitz** [comment]
Hi
The assumption is clientConfig is not null and has been constructed through xml configuration. It is checked in if condition and then it is used by the builder. Why do you call my fix as "null"?

Before this change it was ignoring the proxy configuration in xml config, and creating an empty default ClientConfiguration.

I hope it clarifies the issue.

Regards
Alitz

**Comment by dibog** [comment]
Hi @alitz,

Sorry, I did not wanted to say your fix is "null". I wanted to say that in your fix you are setting the client context to null. But now looking again at it: I see that I have there an typo. When I looked at the if I always saw a `clientConfig==null` but in reality it said `clientConfig!=null`.

Your correction is totally correct. Thanks for the correction, I will merge your change and release a new version.

Best regards,
Dieter

**Comment by dibog** [comment]
This fix is available within cloudwatch-logback-appender-1.0.3.jar.

**Pull request merged**
